---
Name: simpler_silverstripe
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'restruct/silverstripe-simpler:client/dist/js/simpler-domevents.js'
    ## jQuery/BootstrapJS/VueJS: to opt-in, include this JS requirement in your module/project config:
#    - 'restruct/silverstripe-simpler:client/dist/js/simpler-silverstripe.js'
